Highlights Page (WIP)
TEDxJNEC/tedx-2021 pull request #67
Opened 2021-02-01 18:13 UTC by riaaajain

created basic masonary layout with dummy images

2021-02-05 21:06 UTC, sohamtamboli approved these changes

2021-02-05 21:08 UTC, sohamtamboli requested changes
Please resolve conflicts in /src/routes/index.jsx

2021-02-06 23:28 UTC, pruthvi2103 approved these changes
LGTM

2021-02-06 23:30 UTC, pruthvi2103 approved these changes
Resolved conflict

2021-02-06 23:31 UTC, merged